#!/usr/bin/env python
################################################################################
#    Created by Oscar Martinez                                                 #
#    martinez@astro.rug.nl                                                     #
################################################################################

# This is just a module containing the naming of the LEEDB tables / column names

# These are widely used strings
NAME = 'NAME'
ID = '_ID'
SEQ = '_SEQ'
LASTCHECK = 'LAST_CHECK'
LASTMODIFICATION = 'LAST_MODIFICATION'

# REFERENCING
PROJECT = 'PROJECT'
ANTTYPE = 'ANTENNA_TYPE'

STATION = 'STATION'
LOCATIONTYPE = 'LOCATION_TYPE'
POSITION = 'POSITION'

BASELINE = 'BASELINE'
STATION1 = 'STATION_1'
STATION2 = 'STATION_2'

LDS = 'LOFAR_DATASET'
INITIALMJD = 'INITIAL_MJD'
FINALMJD = 'FINAL_MJD'
INITIALUTC = 'INITIAL_UTC'
FINALUTC = 'FINAL_UTC'

LDSHASSTATION = 'LOFAR_DATASET_HAS_STATION' 

FIELD = 'FIELD'

LDSB = 'LOFAR_DATASET_BEAM'
BEAMINDEX = 'BEAM_INDEX'
PHASEDIRRA = 'PHASE_DIRECTION_RA'
PHASEDIRDEC = 'PHASE_DIRECTION_DEC'

STORE = 'STORE'

LDSBP = 'LOFAR_DATASET_BEAM_PRODUCT'
INTTIME = 'INTEGRATION_TIME'
NUMCHAN = 'NUMBER_CHANNELS'
VERSION = 'PRODUCT_VERSION'
RAW = 'RAW'
TAR = 'TAR'
BVF = 'BVF'
DESCR = 'DESCRIPTION'
MAINUSER = 'MAIN_USER'
ADDDATE = 'ADD_DATE'
FLAGGED = 'FLAGGED'
AVERAGED = 'AVERAGED'
CALIBRATED = 'CALIBRATED'
DIRDEPCAL = 'DIR_DEP_CALIBRATION'
DIRINDEPCAL = 'DIR_INDEP_CALIBRATION'

MS = 'MEASUREMENTSET'
SBINDEX = 'SB_INDEX'
CENTFREQ = 'CENTRAL_FREQUENCY'
BW = 'BANDWIDTH'

PARENTPATH = 'PARENT_PATH'

HOST = 'STORE_HOST'
REQUIRESUPDATE = 'REQUIRES_UPDATE'
USAGEMON = 'USAGE_MONITOR'
GPUUSAGEMON = 'GPU_USAGE_MONITOR'
STORAGEMON = 'STORAGE_MONITOR'
NETMON = 'NET_MONITOR'

MSP = 'MEASUREMENTSET_PRODUCT'
SIZE = 'PRODUCT_SIZE'

# APPLICATION
APPRUN = 'APPLICATION_RUN'
ORDERINDEX = 'ORDER_INDEX'
APPNAME = 'APP_NAME'

APPFILE = 'APPLICATION_FILE'
FILEPATH = 'FILE_PATH'

# DIAGNOSTIC
CORR = 'CORRELATION'

GAIN = 'GAIN'
DIRRA = 'DIRECTION_RA'
DIRDEC = 'DIRECTION_DEC'
FSTEP  = 'FREQ_STEP'
TSTEP  = 'TIME_STEP'
VALUES = 'VALUES'

QKIND = 'QUALITY_KIND'
QTSTAT = 'QUALITY_TIME_STATISTIC'
QFSTAT = 'QUALITY_FREQUENCY_STATISTIC'
QBSTAT = 'QUALITY_BASELINE_STATISTIC'

# MOV
GAINMOVIE = 'GAIN_MOVIE'
XAXIS = 'XAXIS'
JONES = 'JONES'
POLAR = 'POLAR'
REFSTATION = 'REFERENCE_STATION'
TIMES = 'TIMES'
CHANNELS = 'CHANNELS'
YRANGE = 'YRANGE'
MESSAGE = 'MESSAGE'

GAINMOVIEHASSTATION = 'GAIN_MOVIE_HAS_STATION'
GAINMOVIEHASMS = 'GAIN_MOVIE_HAS_MEASUREMENTSET'

DELAY = 'DELAY'


# METADATA (FUNCTIONS)
LDSMETA = 'LOFAR_DATASET_META'
LDSNUMBEAMS = 'LDS_NUMBER_BEAMS'
LDSDURATION = 'LDS_DURATION'
LDSFIELDS = 'LDS_FIELDS'
LDSMAINFIELD = 'LDS_MAIN_FIELD'
LDSNUMSTATIONS = 'LDS_NUMBER_STATIONS'
LDSNUMSB = 'LDS_NUMBER_SBS'
LDSNUMMSP = 'LDS_NUMBER_MEASUREMENTSET_PRODUCTS'
LDSTOTALSIZE = 'LDS_TOTAL_SIZE'
LDSMINCENTFREQ = 'LDS_MINIMUM_CENTRAL_FREQUENCY'
LDSMAXCENTFREQ = 'LDS_MAXIMUM_CENTRAL_FREQUENCY'
LDSHASGAIN = 'LDS_HAS_GAIN'
LDSHASQUALITY = 'LDS_HAS_QUALITY'
LDSHASGAINMOVIE = 'LDS_HAS_GAIN_MOVIE'

LDSBMETA = 'LOFAR_DATASET_BEAM_META'
LDSBNUMSB = 'LDSB_NUMBER_SBS' 
LDSBNUMLDSBP = 'LDSB_NUMBER_LDSBP'
LDSBNUMMSP = 'LDSB_NUMBER_MEASUREMENTSET_PRODUCTS'
LDSBTOTALSIZE = 'LDSB_TOTAL_SIZE'
LDSBMINCENTFREQ = 'LDSB_MINIMUM_CENTRAL_FREQUENCY'
LDSBMAXCENTFREQ = 'LDSB_MAXIMUM_CENTRAL_FREQUENCY'
LDSBHASGAIN = 'LDSB_HAS_GAIN'
LDSBHASQUALITY = 'LDSB_HAS_QUALITY'
LDSBHASGAINMOVIE = 'LDSB_HAS_GAIN_MOVIE'

LDSBPMETA = 'LOFAR_DATASET_BEAM_PRODUCT_META'
LDSBPNUMMSP = 'LDSBP_NUMBER_MEASUREMENTSET_PRODUCTS'
LDSBPTOTALSIZE = 'LDSBP_TOTAL_SIZE'
LDSBPLASTMODIFICATION = 'LDSBP_LAST_MODIFICATION'
LDSBPMINCENTFREQ = 'LDSBP_MINIMUM_CENTRAL_FREQUENCY'
LDSBPMAXCENTFREQ = 'LDSBP_MAXIMUM_CENTRAL_FREQUENCY'
LDSBPHASGAIN = 'LDSBP_HAS_GAIN'
LDSBPHASQUALITY = 'LDSBP_HAS_QUALITY'
LDSBPHASGAINMOVIE = 'LDSBP_HAS_GAIN_MOVIE'

MSMETA = 'MEASUREMENTSET_META'
MSHASMSP = 'MS_HAS_MSP'
MSHASGAIN = 'MS_HAS_GAIN'
MSHASQUALITY = 'MS_HAS_QUALITY'
MSHASGAINMOVIE = 'MS_HAS_GAIN_MOVIE'

# The temporal join tables for the queries
LDSJOINED = 'LDS_Q'
LDSBJOINED = 'LDSB_Q'
LDSBPJOINED = 'LDSBP_Q'
MSJOINED = 'MS_Q'

# Keys for the different query types
LDSHASSTATION_KEY = 'LDSHASSTATION'
LDS_KEY = 'LDS'
LDSB_KEY = 'LDSB'
LDSBP_KEY = 'LDSBP'
MS_KEY = 'MS'
MSP_KEY = 'MSP'
GAIN_KEY = 'GAIN'
QTS_KEY = 'QTS'
QFS_KEY = 'QFS'
QBS_KEY = 'QBS'
GAINMOVIE_KEY = 'GAINMOVIE'

NUMSELSTATIONS = 'NUM_SEL_STATIONS'

ALLTABLES = [PROJECT, ANTTYPE, LDS, STATION, LDSHASSTATION, BASELINE+SEQ, BASELINE, FIELD, LDSB+SEQ, LDSB,
              STORE, LDSBP+SEQ, LDSBP, MS+SEQ, MS, HOST, PARENTPATH, MSP+SEQ, MSP, APPRUN+SEQ, APPRUN, APPFILE+SEQ, APPFILE,
              GAINMOVIE+SEQ, GAINMOVIE, GAINMOVIEHASMS, GAINMOVIEHASSTATION, MSMETA, LDSBPMETA, LDSBMETA, LDSMETA,
              LDSJOINED, LDSBJOINED, LDSBPJOINED, MSJOINED,
              GAIN+SEQ, QKIND+SEQ, QKIND, QTSTAT+SEQ, QFSTAT+SEQ, QBSTAT+SEQ, GAIN, QTSTAT, QFSTAT, QBSTAT]